# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

# Commands to be run before your environment runs.
before_script:

# Commands you want to run that will verify your build.
script: 
  - rm composer.lock
  - composer install
  - composer require php-coveralls/php-coveralls
  - mkdir -p build/logs
  - vendor/bin/phpunit

# Execute another command after success of the script.
after_success:
  - vendor/bin/php-coveralls -v

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always